spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      idle-timeout: 30000
      min-idle: 5
      max-lifetime: 1800000
      auto-commit: true

logging:
  level:
    com.zaxxer.hikari: DEBUG

server:
  port: 8083